plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "com.example.minesweeperhandasattochna"
    compileSdk 34

    defaultConfig {
        applicationId "com.example.minesweeperhandasattochna"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation libs.firebase.database
    implementation libs.material.v190
    implementation libs.firebase.auth
    implementation libs.appcompat
    implementation libs.firebase.storage
    implementation libs.glide
    annotationProcessor libs.compiler
    implementation libs.recyclerview
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.gridlayout
    implementation libs.play.services.games
    implementation libs.play.services.auth
}

apply plugin: 'com.google.gms.google-services'
